# -*- coding: utf-8 -*-
"""emotion_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JlGPYXrAgHBAl3geuv2biroe20w8J-o

# Emotion Detection Using Machine Learning

## Project Overview

This project focuses on detecting emotions expressed in text using machine learning techniques. The dataset contains text sentences along with their corresponding emotion labels. The objective is to preprocess the textual data, convert the text into numerical features, train different machine learning models, and compare their classification performance.

The project follows a sequence of steps including data loading, data inspection, emotion label encoding, text preprocessing, feature extraction, model training, prediction, and evaluation.

## Importing Required Libraries

The first step is to import the Python libraries required for data manipulation, numerical operations, visualisation, and analysis. NumPy is imported for numerical operations, while Pandas is used to load and manipulate the dataset. Matplotlib and Seaborn are also imported for data visualisation when required.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Uploading the Dataset

The dataset is uploaded into the Google Colab environment using the `files` module provided by Google Colab. The `files.upload()` function allows a local dataset file to be selected and uploaded so that it can be accessed during the analysis.

"""

from google.colab import files

uploaded = files.upload()

"""## Loading the Dataset

The uploaded dataset is stored in a text file named `train.txt`. The Pandas `read_csv()` function is used to load the file into a DataFrame.

The dataset uses a semicolon (`;`) as the separator between the text and emotion fields. Since the file does not contain column headings, `header=None` is used. The two columns are then explicitly named `text` and `emotion`, where `text` represents the input sentence and `emotion` represents its associated emotion category.


"""

df = pd.read_csv('train.txt',sep =';',header = None, names = ['text', 'emotion'])

"""## Initial Dataset Inspection

The first few records of the dataset are displayed using the `head()` function. This provides an initial view of the structure and contents of the dataset and allows us to verify that the data has been loaded correctly.

The dataset contains two main fields: the textual input and its corresponding emotion label.

"""

df.head()

"""## Checking for Missing Values

Before beginning the preprocessing stage, the dataset is checked for missing values. The `isnull().sum()` function calculates the number of missing values present in each column.

Identifying missing values is important because incomplete text or emotion labels could affect the preprocessing and model training stages.

"""

df.isnull().sum()

"""## Encoding Emotion Labels

Machine learning models require numerical target labels rather than textual category names. Therefore, the unique emotion categories in the dataset are first identified.

A dictionary called `emotion_numbers` is then created to assign a numerical value to each unique emotion. The original emotion labels are subsequently mapped to their corresponding numerical values using the Pandas `map()` function.

This converts the categorical emotion labels into numerical values that can be used as the target variable during model training.

"""

unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

"""## Reviewing the Encoded Dataset

The complete DataFrame is displayed to verify that the emotion labels have been successfully converted from their original categorical names into numerical values.

At this stage, the dataset contains the original text alongside its newly encoded numerical emotion label.

"""

df

df['text'] = df['text'].apply(lambda x : x.lower())

"""## Removing Punctuation

Punctuation marks are removed from the text because they are generally not required for identifying the emotion expressed in the sentence in this classification task.

The Python `string` module provides a collection of standard punctuation characters. A custom function called `remove_punc()` is created using `str.translate()` and a translation table to remove these punctuation characters from the text.

"""

import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

"""## Applying Punctuation Removal

The `remove_punc()` function created in the previous step is applied to every text entry in the dataset.

This removes punctuation throughout the text while retaining the remaining characters and words for further preprocessing.

"""

df['text'] = df['text'].apply(remove_punc)

"""## Removing Numbers

Numbers are removed from the text as part of the preprocessing process. A custom function called `remove_numbers()` examines each character in a text string and retains only characters that are not numerical digits.

Removing numerical values reduces potentially unnecessary features and keeps the focus of the model on the textual information used for emotion classification.

"""

def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

"""## Removing Emojis and Non-ASCII Characters

The next preprocessing step removes emojis and other non-ASCII characters from the text.

The `remove_emojis()` function checks each character using Python's `isascii()` method. Characters recognised as ASCII are retained, while non-ASCII characters are removed.

This creates a more consistent textual representation before the data is converted into numerical features.

"""

def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

"""## Preparing Natural Language Processing

Natural Language Toolkit (NLTK) is introduced to support natural language processing operations. NLTK provides resources and tools that can be used for processing and analysing human language.

In this project, NLTK is used to access English stopwords for the text-cleaning stage.

"""

import nltk

"""## Importing Stopwords

The NLTK stopwords corpus is imported so that commonly occurring English words that provide limited information for the classification task can be identified.

The `word_tokenize` function is also imported as part of the available NLTK text-processing tools, although the subsequent custom preprocessing function uses Python's `split()` method to separate the text into words.

"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

"""## Downloading Required NLTK Resources

The required NLTK resources are downloaded into the Google Colab environment. The `punkt` resource supports tokenisation functionality, while the `stopwords` resource provides lists of commonly used words for different languages.

The English stopword list will be used in the next stage of text preprocessing.

"""

nltk.download('punkt')
nltk.download('stopwords')

"""## Creating the English Stopword Set

The English stopwords provided by NLTK are loaded and converted into a Python set.

A set provides an efficient way of checking whether individual words belong to the collection of stopwords during the text-cleaning process.

"""

stop_words = set(stopwords.words('english'))

"""## Inspecting the Text Before Stopword Removal

An individual text record is displayed to observe the current state of the text after the earlier preprocessing operations.

This provides a reference point for comparing the text before and after stopword removal.

"""

df.loc[1]['text']

"""## Removing Stopwords

A custom function called `remove()` is created to remove English stopwords from the text.

The text is first separated into individual words using the `split()` method. Each word is then checked against the previously created set of English stopwords. Words that are not present in the stopword set are retained, and the remaining words are joined back together to form the cleaned sentence.

Removing common words helps reduce the number of features that the machine learning models need to process and allows the representation to focus more on informative words.

"""

def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

"""## Applying Stopword Removal to the Dataset

The `remove()` function is applied to every text entry in the DataFrame.

At this stage, the text has undergone several preprocessing operations: conversion to lowercase, removal of punctuation, removal of numbers, removal of non-ASCII characters, and removal of English stopwords.

"""

df['text'] = df['text'].apply(remove)

"""## Inspecting the Cleaned Text

The same text record is displayed again after stopword removal.

Comparing this output with the earlier version allows the effect of the preprocessing process to be observed and confirms that common stopwords have been removed from the text.

"""

df.loc[1]['text']

"""## Reviewing the Preprocessed Dataset

The first few records are displayed again to review the dataset after completing the main text preprocessing steps.

The text column now contains cleaned text, while the emotion column contains numerical labels that can be used as the target variable for machine learning.

"""

df.head()

"""## Splitting the Dataset into Training and Testing Sets

The preprocessed dataset is divided into training and testing subsets using Scikit-learn's `train_test_split()` function.

The text is used as the input feature (`X`), while the encoded emotion is used as the target variable (`y`). The `test_size=0.20` parameter reserves 20% of the data for testing and uses the remaining 80% for training.

A `random_state` of 42 is specified to ensure that the same split can be reproduced when the code is executed again.

The training data will be used to build the machine learning models, while the unseen testing data will be used to evaluate their performance.

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

"""## Model 1: Bag-of-Words with Multinomial Naive Bayes

### Converting Text into Numerical Features

Machine learning algorithms cannot directly process raw text. Therefore, the preprocessed text must first be converted into numerical feature representations.

The first approach uses the **Bag-of-Words (BoW)** technique through Scikit-learn's `CountVectorizer`. This method represents text based on the frequency of words appearing in the documents.

The vectoriser is fitted only on the training data and is then used to transform both the training and testing text into numerical feature matrices.

### Training the Naive Bayes Model

A **Multinomial Naive Bayes** classifier is then created and trained using the Bag-of-Words representation of the training data.

Multinomial Naive Bayes is commonly used for text classification because it can work with discrete word-frequency features.

### Making Predictions and Evaluating the Model

After training, the model predicts the emotion labels for the test data. The `accuracy_score()` function is then used to compare the predicted labels with the actual test labels.

Accuracy represents the proportion of test observations that were classified correctly.

"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


bow_accuracy = accuracy_score(y_test, pred_bow)
print(bow_accuracy)

"""## Inspecting the Predictions

The predicted emotion labels generated by the first Naive Bayes model are displayed.

These predictions represent the numerical emotion categories assigned by the model to the text contained in the testing dataset.

"""

pred_bow

"""## Model 2: TF-IDF with Multinomial Naive Bayes

A second text representation technique is now introduced using **Term Frequency–Inverse Document Frequency (TF-IDF)**.

Unlike Bag-of-Words, which primarily represents the frequency of words, TF-IDF assigns weights based on how important a word is within a document relative to the overall collection of documents.

The `TfidfVectorizer` is fitted using the training text and is then used to transform both the training and testing data.

A second Multinomial Naive Bayes model is trained using these TF-IDF features. This allows the performance of Naive Bayes using TF-IDF to be evaluated and compared with the earlier Bag-of-Words approach.

"""

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

"""## Generating Predictions

The trained TF-IDF-based Multinomial Naive Bayes model is used to predict the emotion labels for the unseen testing data.

The resulting predictions are stored in `y_pred` and will be compared with the actual test labels during the evaluation stage.

"""

y_pred = nb2_model.predict(X_test_tfidf)

"""## Evaluating Model Performance

The accuracy of the second model is calculated using the actual test labels and the predictions generated by the TF-IDF-based Naive Bayes classifier.

This accuracy can subsequently be compared with the accuracy obtained from the Bag-of-Words Naive Bayes model.

"""

tfidf_nb_accuracy = accuracy_score(y_test, y_pred)
print(tfidf_nb_accuracy)

"""## Model 3: Logistic Regression

A third machine learning approach is introduced using **Logistic Regression**.

Logistic Regression is a supervised machine learning algorithm that can be used for classification problems. In this project, it is used to classify text into the numerical emotion categories created during the preprocessing stage.

The model will use the TF-IDF features generated previously.

"""

from sklearn.linear_model import LogisticRegression

"""## Initialising the Logistic Regression Model

A Logistic Regression classifier is initialised with `max_iter=1000`.

The maximum number of iterations controls how many optimisation steps the algorithm can perform while fitting the model. A value of 1000 provides the model with sufficient iterations to attempt convergence during training.

"""

logistic_model = LogisticRegression(max_iter=1000)

"""## Training the Logistic Regression Model

The Logistic Regression model is trained using the TF-IDF representation of the training dataset.

During training, the model learns relationships between the numerical text features and the corresponding emotion labels. These learned relationships are then used to classify previously unseen text in the testing dataset.

"""

logistic_model.fit(X_train_tfidf,y_train)

"""## Generating Predictions

The trained Logistic Regression model is used to predict emotion labels for the testing dataset.

The predictions are stored in `log_pred` and represent the emotion categories predicted by the model for the unseen test samples.

"""

log_pred = logistic_model.predict(X_test_tfidf)

"""## Evaluating the Logistic Regression Model

The accuracy of the Logistic Regression classifier is calculated by comparing its predictions with the actual emotion labels in the testing dataset.

This provides the final model accuracy required for comparison with the two Multinomial Naive Bayes approaches.

"""

logistic_accuracy = accuracy_score(y_test, log_pred)
print(logistic_accuracy)

"""# Model Comparison and Conclusion

## Model Comparison

Three machine learning approaches were implemented for emotion classification:

1. **Multinomial Naive Bayes with Bag-of-Words**
2. **Multinomial Naive Bayes with TF-IDF**
3. **Logistic Regression with TF-IDF**

Each model was trained using the same training and testing split, allowing their classification accuracy to be compared using the same evaluation metric.

The accuracy results obtained from the three models should be reviewed to determine which approach performed best on the testing dataset.

## Conclusion

This project demonstrated an end-to-end machine learning approach for detecting emotions from text. The process began with loading and inspecting the dataset, followed by encoding the emotion categories into numerical labels.

The text data was then cleaned through several preprocessing stages, including converting text to lowercase, removing punctuation, numbers, non-ASCII characters, and English stopwords.

The cleaned text was converted into numerical representations using both Bag-of-Words and TF-IDF techniques. These representations were then used to train Multinomial Naive Bayes and Logistic Regression classification models.

Finally, the models were evaluated using accuracy on the unseen testing data. Comparing the results provides an indication of which combination of text representation and machine learning algorithm was most effective for the emotion detection task.

"""

